name: "Addon Factory ORT Addon"
description: "Produce third party component reports"
runs:
  using: "docker"
  image: "docker://ghcr.io/khulnasoft/addonfactory-ort-action:v1.6.0"
inputs:
  args:
    description: Additional arguments to the scanner
    required: false
  WorkDir:
    description: Set the scan directory relative to the project
    required: false
    default: .
  UsePython3:
    description: Set the version of python 3 ie (3.7,3.8,3.9)
    required: false
